<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = [
            ['name' => "Aba",'state_id' => 1],
            ['name' => "Amaigbo",'state_id' => 1],
            ['name' => "Arochukwu",'state_id' => 1],
            ['name' => "Bende",'state_id' => 1],
            ['name' => "Ohafia",'state_id' => 1],
            ['name' => "Okwe",'state_id' => 1],
            ['name' => "Umuahia",'state_id' => 1],
            ['name' => "Demsa",'state_id' => 3],
            ['name' => "Ganye",'state_id' => 3],
            ['name' => "Girei",'state_id' => 3],
            ['name' => "Gombi",'state_id' => 3],
            ['name' => "Jada",'state_id' => 3],
            ['name' => "Jimeta",'state_id' => 3],
            ['name' => "Lamurde",'state_id' => 3],
            ['name' => "Madagala",'state_id' => 3],
            ['name' => "Maiha",'state_id' => 3],
            ['name' => "Mubi",'state_id' => 3],
            ['name' => "Ngurore",'state_id' => 3],
            ['name' => "Numan",'state_id' => 3],
            ['name' => "Shelleng",'state_id' => 3],
            ['name' => "Song",'state_id' => 3],
            ['name' => "Toungo",'state_id' => 3],
            ['name' => "Yola",'state_id' => 3],
            ['name' => "Aguata",'state_id' => 5],
            ['name' => "Agulu",'state_id' => 5],
            ['name' => "Anambra",'state_id' => 5],
            ['name' => "Awka",'state_id' => 5],
            ['name' => "Enugu Ukwu",'state_id' => 5],
            ['name' => "Igbo Ukwu",'state_id' => 5],
            ['name' => "Ihiala",'state_id' => 5],
            ['name' => "Nkpor",'state_id' => 5],
            ['name' => "Nnewi",'state_id' => 5],
            ['name' => "Obosi",'state_id' => 5],
            ['name' => "Okija",'state_id' => 5],
            ['name' => "Okpoko",'state_id' => 5],
            ['name' => "Onitsha",'state_id' => 5],
            ['name' => "Ozubulu",'state_id' => 5],
            ['name' => "Uga",'state_id' => 5],
            ['name' => "Alkaleri",'state_id' => 6],
            ['name' => "Azare",'state_id' => 6],
            ['name' => "Bauchi",'state_id' => 6],
            ['name' => "Bogoro",'state_id' => 6],
            ['name' => "Bununu Dass",'state_id' => 6],
            ['name' => "Darazo",'state_id' => 6],
            ['name' => "Gamawa",'state_id' => 6],
            ['name' => "Ganjuwa",'state_id' => 6],
            ['name' => "Jamari",'state_id' => 6],
            ['name' => "Katagum",'state_id' => 6],
            ['name' => "Misau",'state_id' => 6],
            ['name' => "Ningi",'state_id' => 6],
            ['name' => "Tafawa Balewa",'state_id' => 6],
            ['name' => "Brass",'state_id' => 7],
            ['name' => "Ekeremor",'state_id' => 7],
            ['name' => "Nembe",'state_id' => 7],
            ['name' => "Yenagoa",'state_id' => 7],
            ['name' => "Aliade",'state_id' => 8],
            ['name' => "Gboko",'state_id' => 8],
            ['name' => "Katsina-Ala",'state_id' => 8],
            ['name' => "Makurdi",'state_id' => 8],
            ['name' => "Otukpo",'state_id' => 8],
            ['name' => "Ukum",'state_id' => 8],
            ['name' => "Zaki Biam",'state_id' => 8],
            ['name' => "Abadan",'state_id' => 9],
            ['name' => "Askira",'state_id' => 9],
            ['name' => "Bama",'state_id' => 9],
            ['name' => "Biu",'state_id' => 9],
            ['name' => "Chibok",'state_id' => 9],
            ['name' => "Damboa",'state_id' => 9],
            ['name' => "Dikwa",'state_id' => 9],
            ['name' => "Gamboru",'state_id' => 9],
            ['name' => "Gubio",'state_id' => 9],
            ['name' => "Gwoza",'state_id' => 9],
            ['name' => "Kaga",'state_id' => 9],
            ['name' => "Kala",'state_id' => 9],
            ['name' => "Konduga",'state_id' => 9],
            ['name' => "Kukawa",'state_id' => 9],
            ['name' => "Mafa",'state_id' => 9],
            ['name' => "Magumeri",'state_id' => 9],
            ['name' => "Maiduguri",'state_id' => 9],
            ['name' => "Marte",'state_id' => 9],
            ['name' => "Monguno",'state_id' => 9],
            ['name' => "Ngala",'state_id' => 9],
            ['name' => "Shani",'state_id' => 9],
            ['name' => "Agbor",'state_id' => 11],
            ['name' => "Asaba",'state_id' => 11],
            ['name' => "Bomadi",'state_id' => 11],
            ['name' => "Burutu",'state_id' => 11],
            ['name' => "Okpe",'state_id' => 11],
            ['name' => "Patani",'state_id' => 11],
            ['name' => "Sapele",'state_id' => 11],
            ['name' => "Ughelli",'state_id' => 11],
            ['name' => "Warri",'state_id' => 11],
            ['name' => "Abakaliki",'state_id' => 12],
            ['name' => "Afikpo",'state_id' => 12],
            ['name' => "Effium",'state_id' => 12],
            ['name' => "Ezza",'state_id' => 12],
            ['name' => "Ishieke",'state_id' => 12],
            ['name' => "Uburu",'state_id' => 12],
            ['name' => "Auchi",'state_id' => 13],
            ['name' => "Benin",'state_id' => 13],
            ['name' => "Ekpoma",'state_id' => 13],
            ['name' => "Igarra",'state_id' => 13],
            ['name' => "Ikpoba",'state_id' => 13],
            ['name' => "Irrua",'state_id' => 13],
            ['name' => "Sabongida",'state_id' => 13],
            ['name' => "Ubiaja",'state_id' => 13],
            ['name' => "Uromi",'state_id' => 13],
            ['name' => "Ado",'state_id' => 14],
            ['name' => "Aramoko",'state_id' => 14],
            ['name' => "Efon Alaye",'state_id' => 14],
            ['name' => "Emure",'state_id' => 14],
            ['name' => "Igbara Odo",'state_id' => 14],
            ['name' => "Igede",'state_id' => 14],
            ['name' => "Ijero",'state_id' => 14],
            ['name' => "Ikere",'state_id' => 14],
            ['name' => "Ikole",'state_id' => 14],
            ['name' => "Ilawe",'state_id' => 14],
            ['name' => "Ipoti",'state_id' => 14],
            ['name' => "Ise",'state_id' => 14],
            ['name' => "Ode",'state_id' => 14],
            ['name' => "Omuo",'state_id' => 14],
            ['name' => "Osi",'state_id' => 14],
            ['name' => "Agwa",'state_id' => 15],
            ['name' => "Aku",'state_id' => 15],
            ['name' => "Awgu",'state_id' => 15],
            ['name' => "Eha Amufu",'state_id' => 15],
            ['name' => "Enugu",'state_id' => 15],
            ['name' => "Enugu Ezike",'state_id' => 15],
            ['name' => "Enugu Ngwo",'state_id' => 15],
            ['name' => "Ezeagu",'state_id' => 15],
            ['name' => "Mberubu",'state_id' => 15],
            ['name' => "Nsukka",'state_id' => 15],
            ['name' => "Oji",'state_id' => 15],
            ['name' => "Udi",'state_id' => 15],
            ['name' => "Ako",'state_id' => 16],
            ['name' => "Deba",'state_id' => 16],
            ['name' => "Duku",'state_id' => 16],
            ['name' => "Garko",'state_id' => 16],
            ['name' => "Gombe",'state_id' => 16],
            ['name' => "Kaltungo",'state_id' => 16],
            ['name' => "Kumo",'state_id' => 16],
            ['name' => "Nafada",'state_id' => 16],
            ['name' => "Pindiga",'state_id' => 16],
            ['name' => "Aboh",'state_id' => 17],
            ['name' => "Etiti",'state_id' => 17],
            ['name' => "Ihite",'state_id' => 17],
            ['name' => "Nkwerre",'state_id' => 17],
            ['name' => "Oguta",'state_id' => 17],
            ['name' => "Okigwe",'state_id' => 17],
            ['name' => "Owerri",'state_id' => 17],
            ['name' => "Babura",'state_id' => 18],
            ['name' => "Birnin Kudu",'state_id' => 18],
            ['name' => "Buji",'state_id' => 18],
            ['name' => "Dutse",'state_id' => 18],
            ['name' => "Garki",'state_id' => 18],
            ['name' => "Gumel",'state_id' => 18],
            ['name' => "Gwaram",'state_id' => 18],
            ['name' => "Gwiwa",'state_id' => 18],
            ['name' => "Hadejia",'state_id' => 18],
            ['name' => "Jahun",'state_id' => 18],
            ['name' => "Kaugama",'state_id' => 18],
            ['name' => "Kazaure",'state_id' => 18],
            ['name' => "Keffin Hausa",'state_id' => 18],
            ['name' => "Kiyawa",'state_id' => 18],
            ['name' => "Maigatari",'state_id' => 18],
            ['name' => "Malammaduri",'state_id' => 18],
            ['name' => "Ringim",'state_id' => 18],
            ['name' => "Sule Tankarkar",'state_id' => 18],
            ['name' => "Taura",'state_id' => 18],
            ['name' => "Birnin Gwari",'state_id' => 19],
            ['name' => "Doka",'state_id' => 19],
            ['name' => "Giwa",'state_id' => 19],
            ['name' => "Gwagwada",'state_id' => 19],
            ['name' => "Hunkuyi",'state_id' => 19],
            ['name' => "Igabi",'state_id' => 19],
            ['name' => "Ikara",'state_id' => 19],
            ['name' => "Jemaa",'state_id' => 19],
            ['name' => "Kachia",'state_id' => 19],
            ['name' => "Kaduna",'state_id' => 19],
            ['name' => "Kafanchan",'state_id' => 19],
            ['name' => "Kagarko",'state_id' => 19],
            ['name' => "Kagoro",'state_id' => 19],
            ['name' => "Kaura",'state_id' => 19],
            ['name' => "Kudan",'state_id' => 19],
            ['name' => "Lere",'state_id' => 19],
            ['name' => "Makarfi",'state_id' => 19],
            ['name' => "Sabon Birnin Gwari",'state_id' => 19],
            ['name' => "Sabongari",'state_id' => 19],
            ['name' => "Sanga",'state_id' => 19],
            ['name' => "Soba",'state_id' => 19],
            ['name' => "Tudun Wada",'state_id' => 19],
            ['name' => "Zangon Katab",'state_id' => 19],
            ['name' => "Zaria",'state_id' => 19],
            ['name' => "Ajingi",'state_id' => 20],
            ['name' => "Albasu",'state_id' => 20],
            ['name' => "Bagwai",'state_id' => 20],
            ['name' => "Bebeji",'state_id' => 20],
            ['name' => "Bichi",'state_id' => 20],
            ['name' => "Bunkure",'state_id' => 20],
            ['name' => "Dambarta",'state_id' => 20],
            ['name' => "Dawakin Tofe",'state_id' => 20],
            ['name' => "Fagge",'state_id' => 20],
            ['name' => "Garko",'state_id' => 20],
            ['name' => "Garun Mallam",'state_id' => 20],
            ['name' => "Gaya",'state_id' => 20],
            ['name' => "Gezawa",'state_id' => 20],
            ['name' => "Gwarzo",'state_id' => 20],
            ['name' => "Kabo",'state_id' => 20],
            ['name' => "Kano",'state_id' => 20],
            ['name' => "Karaye",'state_id' => 20],
            ['name' => "Kibiya",'state_id' => 20],
            ['name' => "Kiru",'state_id' => 20],
            ['name' => "Kumbotso",'state_id' => 20],
            ['name' => "Kunchi",'state_id' => 20],
            ['name' => "Kura",'state_id' => 20],
            ['name' => "Madobi",'state_id' => 20],
            ['name' => "Makoda",'state_id' => 20],
            ['name' => "Nassarawa",'state_id' => 20],
            ['name' => "Rano",'state_id' => 20],
            ['name' => "Rimin Gado",'state_id' => 20],
            ['name' => "Shanono",'state_id' => 20],
            ['name' => "Sumaila",'state_id' => 20],
            ['name' => "Takai",'state_id' => 20],
            ['name' => "Tofa",'state_id' => 20],
            ['name' => "Tudun Wada",'state_id' => 20],
            ['name' => "Wudil",'state_id' => 20],
            ['name' => "Bakori",'state_id' => 21],
            ['name' => "Batsari",'state_id' => 21],
            ['name' => "Bindawa",'state_id' => 21],
            ['name' => "Cheranchi",'state_id' => 21],
            ['name' => "Dan Dume",'state_id' => 21],
            ['name' => "Danja",'state_id' => 21],
            ['name' => "Daura",'state_id' => 21],
            ['name' => "Dutsi",'state_id' => 21],
            ['name' => "Dutsin Ma",'state_id' => 21],
            ['name' => "Faskari",'state_id' => 21],
            ['name' => "Funtua",'state_id' => 21],
            ['name' => "Ingawa",'state_id' => 21],
            ['name' => "Jibiya",'state_id' => 21],
            ['name' => "Kangiwa",'state_id' => 21],
            ['name' => "Kankara",'state_id' => 21],
            ['name' => "Kankiya",'state_id' => 21],
            ['name' => "Katsina",'state_id' => 21],
            ['name' => "Kurfi",'state_id' => 21],
            ['name' => "Malumfashi",'state_id' => 21],
            ['name' => "Mani",'state_id' => 21],
            ['name' => "Mashi",'state_id' => 21],
            ['name' => "Musawa",'state_id' => 21],
            ['name' => "Rimi",'state_id' => 21],
            ['name' => "Sandamu",'state_id' => 21],
            ['name' => "Zango",'state_id' => 21],
            ['name' => "Argungu",'state_id' => 22],
            ['name' => "Augie",'state_id' => 22],
            ['name' => "Bagudo",'state_id' => 22],
            ['name' => "Birnin Kebbi",'state_id' => 22],
            ['name' => "Birnin Yauri",'state_id' => 22],
            ['name' => "Bunza",'state_id' => 22],
            ['name' => "Fakai",'state_id' => 22],
            ['name' => "Gwandu",'state_id' => 22],
            ['name' => "Jega",'state_id' => 22],
            ['name' => "Kalgo",'state_id' => 22],
            ['name' => "Koko",'state_id' => 22],
            ['name' => "Maiyema",'state_id' => 22],
            ['name' => "Sakaba",'state_id' => 22],
            ['name' => "Shanga",'state_id' => 22],
            ['name' => "Suru",'state_id' => 22],
            ['name' => "Wasagu",'state_id' => 22],
            ['name' => "Zuru",'state_id' => 22],
            ['name' => "Ajaokuta",'state_id' => 23],
            ['name' => "Ankpa",'state_id' => 23],
            ['name' => "Dekina",'state_id' => 23],
            ['name' => "Idah",'state_id' => 23],
            ['name' => "Kabba",'state_id' => 23],
            ['name' => "Koton-Karifi",'state_id' => 23],
            ['name' => "Kuroro",'state_id' => 23],
            ['name' => "Lokoja",'state_id' => 23],
            ['name' => "Mopa",'state_id' => 23],
            ['name' => "Ogaminana",'state_id' => 23],
            ['name' => "Ogori",'state_id' => 23],
            ['name' => "Okene",'state_id' => 23],
            ['name' => "Ajasse",'state_id' => 24],
            ['name' => "Ilorin",'state_id' => 24],
            ['name' => "Jebba",'state_id' => 24],
            ['name' => "Kaiama",'state_id' => 24],
            ['name' => "Lafiagi",'state_id' => 24],
            ['name' => "Offa",'state_id' => 24],
            ['name' => "Pategi",'state_id' => 24],
            ['name' => "Apapa",'state_id' => 25],
            ['name' => "Badagri",'state_id' => 25],
            ['name' => "Epe",'state_id' => 25],
            ['name' => "Ibeju",'state_id' => 25],
            ['name' => "Iganmi",'state_id' => 25],
            ['name' => "Ikeja",'state_id' => 25],
            ['name' => "Ikorodu",'state_id' => 25],
            ['name' => "Lagos",'state_id' => 25],
            ['name' => "Ojo",'state_id' => 25],
            ['name' => "Surulere",'state_id' => 25],
            ['name' => "Akwanga",'state_id' => 26],
            ['name' => "Awe",'state_id' => 26],
            ['name' => "Doma",'state_id' => 26],
            ['name' => "Keana",'state_id' => 26],
            ['name' => "Keffi",'state_id' => 26],
            ['name' => "Lafia",'state_id' => 26],
            ['name' => "Nassarawa",'state_id' => 26],
            ['name' => "Obi",'state_id' => 26],
            ['name' => "Toto",'state_id' => 26],
            ['name' => "Wamba",'state_id' => 26],
            ['name' => "Agale",'state_id' => 27],
            ['name' => "Babana",'state_id' => 27],
            ['name' => "Bida",'state_id' => 27],
            ['name' => "Bosso",'state_id' => 27],
            ['name' => "Chanchaga",'state_id' => 27],
            ['name' => "Gbako",'state_id' => 27],
            ['name' => "Kontagora",'state_id' => 27],
            ['name' => "Lapai",'state_id' => 27],
            ['name' => "Minna",'state_id' => 27],
            ['name' => "Mokwa",'state_id' => 27],
            ['name' => "New Bussa",'state_id' => 27],
            ['name' => "Rijau",'state_id' => 27],
            ['name' => "Shiroro",'state_id' => 27],
            ['name' => "Suleja",'state_id' => 27],
            ['name' => "Wushishi",'state_id' => 27],
            ['name' => "Abeokuta",'state_id' => 28],
            ['name' => "Ado Odo",'state_id' => 28],
            ['name' => "Agbara",'state_id' => 28],
            ['name' => "Aiyetoro",'state_id' => 28],
            ['name' => "Ewekoro",'state_id' => 28],
            ['name' => "Ifo",'state_id' => 28],
            ['name' => "Ijebu Igbo",'state_id' => 28],
            ['name' => "Ijebu Ode",'state_id' => 28],
            ['name' => "Ikene",'state_id' => 28],
            ['name' => "Ilaro",'state_id' => 28],
            ['name' => "Ipokia",'state_id' => 28],
            ['name' => "Odogbolu",'state_id' => 28],
            ['name' => "Owode",'state_id' => 28],
            ['name' => "Sango Ota",'state_id' => 28],
            ['name' => "Shagamu",'state_id' => 28],
            ['name' => "Akure",'state_id' => 29],
            ['name' => "Idanre",'state_id' => 29],
            ['name' => "Ikare",'state_id' => 29],
            ['name' => "Irele",'state_id' => 29],
            ['name' => "Odigbo",'state_id' => 29],
            ['name' => "Oka",'state_id' => 29],
            ['name' => "Okitipupa",'state_id' => 29],
            ['name' => "Ondo",'state_id' => 29],
            ['name' => "Owo",'state_id' => 29],
            ['name' => "Apomu",'state_id' => 30],
            ['name' => "Ede",'state_id' => 30],
            ['name' => "Ejigbo",'state_id' => 30],
            ['name' => "Erin-Oshogbo",'state_id' => 30],
            ['name' => "Gbongan",'state_id' => 30],
            ['name' => "Ife",'state_id' => 30],
            ['name' => "Ifon Osun",'state_id' => 30],
            ['name' => "Ijesha",'state_id' => 30],
            ['name' => "Ikire",'state_id' => 30],
            ['name' => "Ikirun",'state_id' => 30],
            ['name' => "Ila",'state_id' => 30],
            ['name' => "Ilesha",'state_id' => 30],
            ['name' => "Ilobu",'state_id' => 30],
            ['name' => "Inisa",'state_id' => 30],
            ['name' => "Iwo",'state_id' => 30],
            ['name' => "Modakeke",'state_id' => 30],
            ['name' => "Oke-Mesi",'state_id' => 30],
            ['name' => "Olorunda",'state_id' => 30],
            ['name' => "Olupona",'state_id' => 30],
            ['name' => "Ore",'state_id' => 30],
            ['name' => "Orolu",'state_id' => 30],
            ['name' => "Oshogbo",'state_id' => 30],
            ['name' => "Oyan",'state_id' => 30],
            ['name' => "Akinyele",'state_id' => 31],
            ['name' => "Egbeda",'state_id' => 31],
            ['name' => "Eruwa",'state_id' => 31],
            ['name' => "Fiditi",'state_id' => 31],
            ['name' => "Ibadan",'state_id' => 31],
            ['name' => "Ibeto",'state_id' => 31],
            ['name' => "Igbo Ora",'state_id' => 31],
            ['name' => "Igboho",'state_id' => 31],
            ['name' => "Iseyin",'state_id' => 31],
            ['name' => "Kajola",'state_id' => 31],
            ['name' => "Kishi",'state_id' => 31],
            ['name' => "Lalupon",'state_id' => 31],
            ['name' => "Ogbomosho",'state_id' => 31],
            ['name' => "Ogo",'state_id' => 31],
            ['name' => "Oke-Iho",'state_id' => 31],
            ['name' => "Oyo",'state_id' => 31],
            ['name' => "Shaki",'state_id' => 31],
            ['name' => "Barakin",'state_id' => 32],
            ['name' => "Bassa",'state_id' => 32],
            ['name' => "Bokkos",'state_id' => 32],
            ['name' => "Bukuru",'state_id' => 32],
            ['name' => "Jos",'state_id' => 32],
            ['name' => "Langtang",'state_id' => 32],
            ['name' => "Pankshin",'state_id' => 32],
            ['name' => "Riyom",'state_id' => 32],
            ['name' => "Shendam",'state_id' => 32],
            ['name' => "Vom",'state_id' => 32],
            ['name' => "Wase",'state_id' => 32],
            ['name' => "Abonnema",'state_id' => 33],
            ['name' => "Abua",'state_id' => 33],
            ['name' => "Ahoada",'state_id' => 33],
            ['name' => "Bonny",'state_id' => 33],
            ['name' => "Bugama",'state_id' => 33],
            ['name' => "Degema",'state_id' => 33],
            ['name' => "Egbema",'state_id' => 33],
            ['name' => "Ogu",'state_id' => 33],
            ['name' => "Okrika",'state_id' => 33],
            ['name' => "Omoko",'state_id' => 33],
            ['name' => "Opobo",'state_id' => 33],
            ['name' => "Oyigbo",'state_id' => 33],
            ['name' => "Port Harcourt",'state_id' => 33],
            ['name' => "Binji",'state_id' => 34],
            ['name' => "Bodinga",'state_id' => 34],
            ['name' => "Dange",'state_id' => 34],
            ['name' => "Gada",'state_id' => 34],
            ['name' => "Goronyo",'state_id' => 34],
            ['name' => "Gwadabawa",'state_id' => 34],
            ['name' => "Illela",'state_id' => 34],
            ['name' => "Kebbe",'state_id' => 34],
            ['name' => "Kware",'state_id' => 34],
            ['name' => "Rabah",'state_id' => 34],
            ['name' => "Raka",'state_id' => 34],
            ['name' => "Sabon Birni",'state_id' => 34],
            ['name' => "Sokoto",'state_id' => 34],
            ['name' => "Tambawel",'state_id' => 34],
            ['name' => "Tureta",'state_id' => 34],
            ['name' => "Wamako",'state_id' => 34],
            ['name' => "Wurno",'state_id' => 34],
            ['name' => "Bali",'state_id' => 35],
            ['name' => "Gashaka",'state_id' => 35],
            ['name' => "Gassol",'state_id' => 35],
            ['name' => "Ibi",'state_id' => 35],
            ['name' => "Jalingo",'state_id' => 35],
            ['name' => "Lau",'state_id' => 35],
            ['name' => "Takum",'state_id' => 35],
            ['name' => "Wukari",'state_id' => 35],
            ['name' => "Yorro",'state_id' => 35],
            ['name' => "Damaturu",'state_id' => 36],
            ['name' => "Fika",'state_id' => 36],
            ['name' => "Gashua",'state_id' => 36],
            ['name' => "Geidam",'state_id' => 36],
            ['name' => "Gorgoram",'state_id' => 36],
            ['name' => "Gujba",'state_id' => 36],
            ['name' => "Gulani",'state_id' => 36],
            ['name' => "Jakusko",'state_id' => 36],
            ['name' => "Matsena",'state_id' => 36],
            ['name' => "Nguru",'state_id' => 36],
            ['name' => "Potiskum",'state_id' => 36],
            ['name' => "Yusufari",'state_id' => 36],
            ['name' => "Anka",'state_id' => 37],
            ['name' => "Bungudu",'state_id' => 37],
            ['name' => "Chafe",'state_id' => 37],
            ['name' => "Gummi",'state_id' => 37],
            ['name' => "Gusau",'state_id' => 37],
            ['name' => "Isa",'state_id' => 37],
            ['name' => "Kaura Namoda",'state_id' => 37],
            ['name' => "Kiyawa",'state_id' => 37],
            ['name' => "Maradun",'state_id' => 37],
            ['name' => "Maru",'state_id' => 37],
            ['name' => "Shinkafe",'state_id' => 37],
            ['name' => "Talata Mafara",'state_id' => 37],
            ['name' => "Zurmi",'state_id' => 37],
            
        ];

        foreach ($cities as $city) {
            City::create(attributes: $city);
        }
    }

}
